### ISSUE TITLE
Explicit Error Sets

### ISSUE THREAD

**Issue by mitchellh** [vancluever/z2d#48]
There are still a variety of functions that use implicit error sets. It'd be good form to convert these to explicit error sets. This makes it easier for downstream users to also use explicit error sets, and to detect when new errors are added.

Example functions:

* `Context.fill`
* `Surface.initPixel`
* `Path.*`

etc.

**Comment by vancluever** [comment]
@mitchellh thanks for this! I think the functions in question are currently that way because they have downstream calls that ultimately yeild errors that I didn't necessarily want to have to plumb too much. _But_ 1) I have a feeling that it's possible that a lot of these go away when #44 is addressed (e.g., much less reliance on call-time memory allocations) and for the ones that don't, or for other situations, I can have these caught and return something in the `InternalError` set instead.

Putting it on the todo!

**Comment by mitchellh** [comment]
> or for other situations, I can have these caught and return something in the InternalError set instead.

Yes, that sounds great.

Also note that if you're using any comptime stuff you can reflect on error sets to get them out if needed. I didn't see any such need but I didn't look very hard either.

**Comment by vancluever** [comment]
Ooh, neat trick, good to know :grin: yeah I don't think it's really necessary in this instance, I definitely think I could do more instead to make opinionated decisions about how errors that aren't necessarily z2d's are handled so that the buck stops at the library. A good exercise all in all!

**Comment by vancluever** [comment]
TODO: #51 greatly reduces the errors emitted by surfaces - `SurfaceError.OutOfRange` can be removed as a result.
